In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
data_1 = pd.read_csv('Multiple Regression.csv')

In [3]:
data_1.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
# extracting the independent variables
x = data_1[['SAT','Rand 1,2,3']]

In [5]:
x.head()

SAT  Rand 1,2,3
0  1714           1
1  1664           3
2  1760           3
3  1685           3
4  1693           2

In [6]:
#Extracting the dependent variable y 
y = data_1['GPA']

In [7]:
reg = LinearRegression()

In [8]:
# fitting the multiple regression
reg.fit(x, y)

LinearRegression()

In [70]:
# Calculating the R^2
reg.score(x,y)

-1383037.8990380396

In [71]:
# Calculating the coefficients
reg.coef_

array([ 0.17181389, -0.00703007])

In [72]:
# calculating the intercept
reg.intercept_

3.330238095238095

In [73]:
# calculating the summary table
summary_table = pd.DataFrame({'features':['SAT','Rand 1,2,3'],'coefficient':reg.coef_,'intercept':reg.intercept_})

In [74]:
summary_table

features  coefficient  intercept
0         SAT     0.171814   3.330238
1  Rand 1,2,3    -0.007030   3.330238

In [75]:
# Exracting new data for prediction
new_data = pd.DataFrame({'SAT':[1714,1664],'Rand 1,2,3':[1,3]})

In [76]:
new_data

SAT  Rand 1,2,3
0  1714           1
1  1664           3

In [77]:
# prediction of GPA with the new_data
reg.predict(new_data)

array([297.81222019, 289.20746542])

In [78]:
y[0:3]

0    2.40
1    2.52
2    2.54
Name: GPA, dtype: float64

In [79]:
# fitting the multiple regression while standardizing the independent variables
scaler = StandardScaler()

In [80]:
scaler.fit(x)

StandardScaler()

In [81]:
scale_x = scaler.transform(x)

In [82]:
scale_x[0:3]

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974]])

In [83]:
reg.fit(scale_x, y)

LinearRegression()

In [84]:
x_coeff = reg.coef_

In [85]:
y_inter = reg.intercept_

In [86]:
summary_table_1 = pd.DataFrame([['SAT'],['Rand 1, 2, 3']],columns=['features']) # arrange the data in row-wise versus column

In [87]:
summary_table_1['coefficient']=x_coeff
summary_table_1['intercept']=y_inter

In [88]:
summary_table_1

features  coefficient  intercept
0           SAT     0.171814   3.330238
1  Rand 1, 2, 3    -0.007030   3.330238

In [ ]:
#summarry_table_all = pd.merge(summary_table,summary_table_1,on='features',how ='outer')

In [90]:
#summarry_table_all

In [91]:
summary_table['x_scale_coefficient']= x_coeff

In [92]:
summary_table['x_scale_intercept']=y_inter

In [93]:
summary_table

features  coefficient  intercept  x_scale_coefficient  x_scale_intercept
0         SAT     0.171814   3.330238             0.171814           3.330238
1  Rand 1,2,3    -0.007030   3.330238            -0.007030           3.330238

In [95]:
#selecting the most important variable
from sklearn.feature_selection import f_regression

In [96]:
sel = f_regression

In [97]:
sel(scale_x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [100]:
sel(scale_x,y)[1][0].round(7)

0.0

In [ ]:
df